# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/joystick.ui'
#
# Created: Mon Jun 29 19:59:28 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_joystickWidget(object):
    def setupUi(self, joystickWidget):
        joystickWidget.setObjectName(_fromUtf8("joystickWidget"))
        joystickWidget.resize(100, 100)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(joystickWidget.sizePolicy().hasHeightForWidth())
        joystickWidget.setSizePolicy(sizePolicy)
        joystickWidget.setMinimumSize(QtCore.QSize(100, 100))
        joystickWidget.setMaximumSize(QtCore.QSize(150, 150))
        joystickWidget.setSizeIncrement(QtCore.QSize(1, 1))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        joystickWidget.setFont(font)
        joystickWidget.setMouseTracking(False)
        joystickWidget.setFocusPolicy(QtCore.Qt.StrongFocus)
        joystickWidget.setAutoFillBackground(False)
        self.layout = QtGui.QVBoxLayout(joystickWidget)
        self.layout.setMargin(0)
        self.layout.setObjectName(_fromUtf8("layout"))
        self.joystickControl = QtGui.QGroupBox(joystickWidget)
        self.joystickControl.setObjectName(_fromUtf8("joystickControl"))
        self.gridLayout = QtGui.QGridLayout(self.joystickControl)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setContentsMargins(2, 2, 5, 2)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.down = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.down.setFont(font)
        self.down.setFrameShape(QtGui.QFrame.StyledPanel)
        self.down.setFrameShadow(QtGui.QFrame.Plain)
        self.down.setScaledContents(True)
        self.down.setAlignment(QtCore.Qt.AlignCenter)
        self.down.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.down.setObjectName(_fromUtf8("down"))
        self.gridLayout.addWidget(self.down, 2, 1, 1, 1)
        self.topleft = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.topleft.setFont(font)
        self.topleft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.topleft.setScaledContents(True)
        self.topleft.setAlignment(QtCore.Qt.AlignCenter)
        self.topleft.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.topleft.setObjectName(_fromUtf8("topleft"))
        self.gridLayout.addWidget(self.topleft, 0, 0, 1, 1)
        self.topright = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.topright.setFont(font)
        self.topright.setFrameShape(QtGui.QFrame.StyledPanel)
        self.topright.setScaledContents(True)
        self.topright.setAlignment(QtCore.Qt.AlignCenter)
        self.topright.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.topright.setObjectName(_fromUtf8("topright"))
        self.gridLayout.addWidget(self.topright, 0, 2, 1, 1)
        self.center = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.center.setFont(font)
        self.center.setFrameShape(QtGui.QFrame.StyledPanel)
        self.center.setScaledContents(True)
        self.center.setAlignment(QtCore.Qt.AlignCenter)
        self.center.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.center.setObjectName(_fromUtf8("center"))
        self.gridLayout.addWidget(self.center, 1, 1, 1, 1)
        self.up = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.up.setFont(font)
        self.up.setFrameShape(QtGui.QFrame.StyledPanel)
        self.up.setScaledContents(True)
        self.up.setAlignment(QtCore.Qt.AlignCenter)
        self.up.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.up.setObjectName(_fromUtf8("up"))
        self.gridLayout.addWidget(self.up, 0, 1, 1, 1)
        self.downright = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.downright.setFont(font)
        self.downright.setFrameShape(QtGui.QFrame.StyledPanel)
        self.downright.setFrameShadow(QtGui.QFrame.Plain)
        self.downright.setScaledContents(True)
        self.downright.setAlignment(QtCore.Qt.AlignCenter)
        self.downright.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.downright.setObjectName(_fromUtf8("downright"))
        self.gridLayout.addWidget(self.downright, 2, 2, 1, 1)
        self.right = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.right.setFont(font)
        self.right.setFrameShape(QtGui.QFrame.StyledPanel)
        self.right.setScaledContents(True)
        self.right.setAlignment(QtCore.Qt.AlignCenter)
        self.right.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.right.setObjectName(_fromUtf8("right"))
        self.gridLayout.addWidget(self.right, 1, 2, 1, 1)
        self.downleft = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.downleft.setFont(font)
        self.downleft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.downleft.setFrameShadow(QtGui.QFrame.Plain)
        self.downleft.setScaledContents(True)
        self.downleft.setAlignment(QtCore.Qt.AlignCenter)
        self.downleft.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.downleft.setObjectName(_fromUtf8("downleft"))
        self.gridLayout.addWidget(self.downleft, 2, 0, 1, 1)
        self.left = QtGui.QLabel(self.joystickControl)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.left.setFont(font)
        self.left.setFrameShape(QtGui.QFrame.StyledPanel)
        self.left.setScaledContents(True)
        self.left.setAlignment(QtCore.Qt.AlignCenter)
        self.left.setTextInteractionFlags(QtCore.Qt.NoTextInteraction)
        self.left.setObjectName(_fromUtf8("left"))
        self.gridLayout.addWidget(self.left, 1, 0, 1, 1)
        self.layout.addWidget(self.joystickControl)

        self.retranslateUi(joystickWidget)
        QtCore.QMetaObject.connectSlotsByName(joystickWidget)

    def retranslateUi(self, joystickWidget):
        joystickWidget.setWindowTitle(_translate("joystickWidget", "Form", None))
        self.joystickControl.setTitle(_translate("joystickWidget", "Joystick", None))
        self.down.setText(_translate("joystickWidget", "↓", None))
        self.topleft.setText(_translate("joystickWidget", "↖︎", None))
        self.topright.setText(_translate("joystickWidget", "↗︎", None))
        self.center.setText(_translate("joystickWidget", "•", None))
        self.up.setText(_translate("joystickWidget", "↑", None))
        self.downright.setText(_translate("joystickWidget", "↘︎", None))
        self.right.setText(_translate("joystickWidget", "→", None))
        self.downleft.setText(_translate("joystickWidget", "↙︎", None))
        self.left.setText(_translate("joystickWidget", "←", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    joystickWidget = QtGui.QWidget()
    ui = Ui_joystickWidget()
    ui.setupUi(joystickWidget)
    joystickWidget.show()
    sys.exit(app.exec_())

