# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/Views.ui'
#
# Created: Sun Jun 28 21:22:59 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_viewsWidget(object):
    def setupUi(self, viewsWidget):
        viewsWidget.setObjectName(_fromUtf8("viewsWidget"))
        viewsWidget.resize(459, 487)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(viewsWidget.sizePolicy().hasHeightForWidth())
        viewsWidget.setSizePolicy(sizePolicy)
        viewsWidget.setMinimumSize(QtCore.QSize(0, 0))
        viewsWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.verticalLayout = QtGui.QVBoxLayout(viewsWidget)
        self.verticalLayout.setMargin(6)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.currentViews = QtGui.QWidget(viewsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentViews.sizePolicy().hasHeightForWidth())
        self.currentViews.setSizePolicy(sizePolicy)
        self.currentViews.setSizeIncrement(QtCore.QSize(3, 3))
        self.currentViews.setObjectName(_fromUtf8("currentViews"))
        self.currentViewsLayout = QtGui.QGridLayout(self.currentViews)
        self.currentViewsLayout.setMargin(0)
        self.currentViewsLayout.setObjectName(_fromUtf8("currentViewsLayout"))
        self.tleft = DCurrentView(self.currentViews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tleft.sizePolicy().hasHeightForWidth())
        self.tleft.setSizePolicy(sizePolicy)
        self.tleft.setAcceptDrops(True)
        self.tleft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tleft.setFrameShadow(QtGui.QFrame.Raised)
        self.tleft.setObjectName(_fromUtf8("tleft"))
        self.tleftLayout = QtGui.QHBoxLayout(self.tleft)
        self.tleftLayout.setMargin(0)
        self.tleftLayout.setObjectName(_fromUtf8("tleftLayout"))
        self.tleftLabel = QtGui.QLabel(self.tleft)
        self.tleftLabel.setStyleSheet(_fromUtf8("color: rgb(102, 102, 102);"))
        self.tleftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.tleftLabel.setObjectName(_fromUtf8("tleftLabel"))
        self.tleftLayout.addWidget(self.tleftLabel)
        self.currentViewsLayout.addWidget(self.tleft, 0, 0, 1, 1)
        self.bleft = DCurrentView(self.currentViews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bleft.sizePolicy().hasHeightForWidth())
        self.bleft.setSizePolicy(sizePolicy)
        self.bleft.setAcceptDrops(True)
        self.bleft.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bleft.setFrameShadow(QtGui.QFrame.Raised)
        self.bleft.setObjectName(_fromUtf8("bleft"))
        self.bleftLayout = QtGui.QHBoxLayout(self.bleft)
        self.bleftLayout.setMargin(0)
        self.bleftLayout.setObjectName(_fromUtf8("bleftLayout"))
        self.bleftLabel = QtGui.QLabel(self.bleft)
        self.bleftLabel.setStyleSheet(_fromUtf8("color: rgb(102, 102, 102);"))
        self.bleftLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.bleftLabel.setObjectName(_fromUtf8("bleftLabel"))
        self.bleftLayout.addWidget(self.bleftLabel)
        self.currentViewsLayout.addWidget(self.bleft, 1, 0, 1, 1)
        self.bright = DCurrentView(self.currentViews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bright.sizePolicy().hasHeightForWidth())
        self.bright.setSizePolicy(sizePolicy)
        self.bright.setAcceptDrops(True)
        self.bright.setFrameShape(QtGui.QFrame.StyledPanel)
        self.bright.setFrameShadow(QtGui.QFrame.Raised)
        self.bright.setObjectName(_fromUtf8("bright"))
        self.brightLayout = QtGui.QHBoxLayout(self.bright)
        self.brightLayout.setMargin(0)
        self.brightLayout.setObjectName(_fromUtf8("brightLayout"))
        self.brightLabel = QtGui.QLabel(self.bright)
        self.brightLabel.setStyleSheet(_fromUtf8("color: rgb(102, 102, 102);"))
        self.brightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.brightLabel.setObjectName(_fromUtf8("brightLabel"))
        self.brightLayout.addWidget(self.brightLabel)
        self.currentViewsLayout.addWidget(self.bright, 1, 1, 1, 1)
        self.tright = DCurrentView(self.currentViews)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tright.sizePolicy().hasHeightForWidth())
        self.tright.setSizePolicy(sizePolicy)
        self.tright.setAcceptDrops(True)
        self.tright.setFrameShape(QtGui.QFrame.StyledPanel)
        self.tright.setFrameShadow(QtGui.QFrame.Raised)
        self.tright.setObjectName(_fromUtf8("tright"))
        self.trightLayout = QtGui.QHBoxLayout(self.tright)
        self.trightLayout.setMargin(0)
        self.trightLayout.setObjectName(_fromUtf8("trightLayout"))
        self.trightLabel = QtGui.QLabel(self.tright)
        self.trightLabel.setStyleSheet(_fromUtf8("color: rgb(102, 102, 102);"))
        self.trightLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.trightLabel.setObjectName(_fromUtf8("trightLabel"))
        self.trightLayout.addWidget(self.trightLabel)
        self.currentViewsLayout.addWidget(self.tright, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.currentViews)
        self.buttonViews = QtGui.QHBoxLayout()
        self.buttonViews.setObjectName(_fromUtf8("buttonViews"))
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonViews.addItem(spacerItem)
        self.four = QtGui.QPushButton(viewsWidget)
        self.four.setMinimumSize(QtCore.QSize(44, 44))
        self.four.setCheckable(True)
        self.four.setAutoExclusive(True)
        self.four.setObjectName(_fromUtf8("four"))
        self.buttonViews.addWidget(self.four)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonViews.addItem(spacerItem1)
        self.vert = QtGui.QPushButton(viewsWidget)
        self.vert.setMinimumSize(QtCore.QSize(44, 44))
        self.vert.setCheckable(True)
        self.vert.setAutoExclusive(True)
        self.vert.setObjectName(_fromUtf8("vert"))
        self.buttonViews.addWidget(self.vert)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonViews.addItem(spacerItem2)
        self.hor = QtGui.QPushButton(viewsWidget)
        self.hor.setMinimumSize(QtCore.QSize(44, 44))
        self.hor.setCheckable(True)
        self.hor.setChecked(True)
        self.hor.setAutoExclusive(True)
        self.hor.setObjectName(_fromUtf8("hor"))
        self.buttonViews.addWidget(self.hor)
        spacerItem3 = QtGui.QSpacerItem(40, 10, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.buttonViews.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.buttonViews)
        self.viewsGroup = QtGui.QGroupBox(viewsWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.viewsGroup.sizePolicy().hasHeightForWidth())
        self.viewsGroup.setSizePolicy(sizePolicy)
        self.viewsGroup.setMinimumSize(QtCore.QSize(0, 92))
        self.viewsGroup.setMaximumSize(QtCore.QSize(16777215, 110))
        self.viewsGroup.setSizeIncrement(QtCore.QSize(1, 1))
        self.viewsGroup.setBaseSize(QtCore.QSize(0, 0))
        self.viewsGroup.setFlat(False)
        self.viewsGroup.setObjectName(_fromUtf8("viewsGroup"))
        self.viewsGroupLayout = QtGui.QHBoxLayout(self.viewsGroup)
        self.viewsGroupLayout.setMargin(0)
        self.viewsGroupLayout.setObjectName(_fromUtf8("viewsGroupLayout"))
        self.availableViews = DAvailableView(self.viewsGroup)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.availableViews.sizePolicy().hasHeightForWidth())
        self.availableViews.setSizePolicy(sizePolicy)
        self.availableViews.setMinimumSize(QtCore.QSize(0, 90))
        self.availableViews.setMaximumSize(QtCore.QSize(16777215, 110))
        self.availableViews.setMouseTracking(False)
        self.availableViews.setAcceptDrops(True)
        self.availableViews.setFrameShape(QtGui.QFrame.NoFrame)
        self.availableViews.setObjectName(_fromUtf8("availableViews"))
        self.availableViewsLayout = QtGui.QHBoxLayout(self.availableViews)
        self.availableViewsLayout.setMargin(3)
        self.availableViewsLayout.setObjectName(_fromUtf8("availableViewsLayout"))
        self.viewsGroupLayout.addWidget(self.availableViews)
        self.pushButton = HButton(self.viewsGroup)
        self.pushButton.setMinimumSize(QtCore.QSize(44, 44))
        self.pushButton.setMaximumSize(QtCore.QSize(44, 44))
        self.pushButton.setMouseTracking(True)
        self.pushButton.setCheckable(True)
        self.pushButton.setDefault(False)
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.viewsGroupLayout.addWidget(self.pushButton)
        self.verticalLayout.addWidget(self.viewsGroup)

        self.retranslateUi(viewsWidget)
        QtCore.QMetaObject.connectSlotsByName(viewsWidget)

    def retranslateUi(self, viewsWidget):
        viewsWidget.setWindowTitle(_translate("viewsWidget", "Form", None))
        self.tleftLabel.setText(_translate("viewsWidget", "Drag any view here", None))
        self.bleftLabel.setText(_translate("viewsWidget", "Drag any view here", None))
        self.brightLabel.setText(_translate("viewsWidget", "Drag any view here", None))
        self.trightLabel.setText(_translate("viewsWidget", "Drag any view here", None))
        self.four.setText(_translate("viewsWidget", "┼", None))
        self.vert.setText(_translate("viewsWidget", "│", None))
        self.hor.setText(_translate("viewsWidget", "─", None))
        self.viewsGroup.setTitle(_translate("viewsWidget", "Available Views", None))
        self.pushButton.setText(_translate("viewsWidget", "-", None))

from utilities.DropView import DCurrentView, DAvailableView
from HoverButtons import HButton
