# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/parameters.ui'
#
# Created: Sun Sep 13 14:36:02 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_AUIParameters(object):
    def setupUi(self, AUIParameters):
        AUIParameters.setObjectName(_fromUtf8("AUIParameters"))
        AUIParameters.resize(241, 669)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(AUIParameters.sizePolicy().hasHeightForWidth())
        AUIParameters.setSizePolicy(sizePolicy)
        AUIParameters.setMaximumSize(QtCore.QSize(250, 524287))
        AUIParameters.setFloating(False)
        AUIParameters.setFeatures(QtGui.QDockWidget.AllDockWidgetFeatures)
        self.AUIParams = QtGui.QWidget()
        self.AUIParams.setObjectName(_fromUtf8("AUIParams"))
        self.verticalLayout = QtGui.QVBoxLayout(self.AUIParams)
        self.verticalLayout.setSpacing(-1)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.contents = QtGui.QTabWidget(self.AUIParams)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.contents.sizePolicy().hasHeightForWidth())
        self.contents.setSizePolicy(sizePolicy)
        self.contents.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.contents.setTabPosition(QtGui.QTabWidget.South)
        self.contents.setObjectName(_fromUtf8("contents"))
        self.Tab1 = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Tab1.sizePolicy().hasHeightForWidth())
        self.Tab1.setSizePolicy(sizePolicy)
        self.Tab1.setObjectName(_fromUtf8("Tab1"))
        self.tab1Layout = QtGui.QVBoxLayout(self.Tab1)
        self.tab1Layout.setSpacing(-1)
        self.tab1Layout.setContentsMargins(0, 20, 0, 0)
        self.tab1Layout.setObjectName(_fromUtf8("tab1Layout"))
        self.groupBox_4 = QtGui.QGroupBox(self.Tab1)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.groupBox_4)
        self.verticalLayout_4.setMargin(1)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.decision_path = QtGui.QLabel(self.groupBox_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.decision_path.setFont(font)
        self.decision_path.setText(_fromUtf8(""))
        self.decision_path.setWordWrap(True)
        self.decision_path.setObjectName(_fromUtf8("decision_path"))
        self.verticalLayout_4.addWidget(self.decision_path)
        self.tab1Layout.addWidget(self.groupBox_4)
        self.user = QtGui.QGroupBox(self.Tab1)
        self.user.setObjectName(_fromUtf8("user"))
        self.userLayout = QtGui.QVBoxLayout(self.user)
        self.userLayout.setSpacing(-1)
        self.userLayout.setMargin(0)
        self.userLayout.setObjectName(_fromUtf8("userLayout"))
        self.userStatus = QtGui.QGroupBox(self.user)
        self.userStatus.setBaseSize(QtCore.QSize(0, 200))
        self.userStatus.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.userStatus.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.userStatus.setFlat(True)
        self.userStatus.setObjectName(_fromUtf8("userStatus"))
        self.userStatusLayout = QtGui.QGridLayout(self.userStatus)
        self.userStatusLayout.setMargin(0)
        self.userStatusLayout.setVerticalSpacing(0)
        self.userStatusLayout.setObjectName(_fromUtf8("userStatusLayout"))
        self.stressLabel = QtGui.QLabel(self.userStatus)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stressLabel.setFont(font)
        self.stressLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.stressLabel.setWordWrap(True)
        self.stressLabel.setObjectName(_fromUtf8("stressLabel"))
        self.userStatusLayout.addWidget(self.stressLabel, 1, 0, 1, 1)
        self.cognitiveLoadLabel = QtGui.QLabel(self.userStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cognitiveLoadLabel.setFont(font)
        self.cognitiveLoadLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.cognitiveLoadLabel.setWordWrap(True)
        self.cognitiveLoadLabel.setObjectName(_fromUtf8("cognitiveLoadLabel"))
        self.userStatusLayout.addWidget(self.cognitiveLoadLabel, 1, 1, 1, 1)
        self.saLabel = QtGui.QLabel(self.userStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.saLabel.setFont(font)
        self.saLabel.setScaledContents(True)
        self.saLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.saLabel.setWordWrap(True)
        self.saLabel.setObjectName(_fromUtf8("saLabel"))
        self.userStatusLayout.addWidget(self.saLabel, 1, 2, 1, 1)
        self.situationAwareness = QtGui.QGroupBox(self.userStatus)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.situationAwareness.setFont(font)
        self.situationAwareness.setTitle(_fromUtf8(""))
        self.situationAwareness.setAlignment(QtCore.Qt.AlignCenter)
        self.situationAwareness.setObjectName(_fromUtf8("situationAwareness"))
        self.gridLayout_9 = QtGui.QGridLayout(self.situationAwareness)
        self.gridLayout_9.setMargin(0)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.label_3 = QtGui.QLabel(self.situationAwareness)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_9.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_2 = QtGui.QLabel(self.situationAwareness)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_9.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtGui.QLabel(self.situationAwareness)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_9.addWidget(self.label_4, 1, 0, 1, 1)
        self.saSlider = QtGui.QSlider(self.situationAwareness)
        self.saSlider.setMinimum(1)
        self.saSlider.setMaximum(3)
        self.saSlider.setPageStep(1)
        self.saSlider.setProperty("value", 2)
        self.saSlider.setOrientation(QtCore.Qt.Vertical)
        self.saSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.saSlider.setTickInterval(1)
        self.saSlider.setObjectName(_fromUtf8("saSlider"))
        self.gridLayout_9.addWidget(self.saSlider, 0, 2, 3, 1)
        self.userStatusLayout.addWidget(self.situationAwareness, 0, 2, 1, 1)
        self.cgnitiveLoad = QtGui.QGroupBox(self.userStatus)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.cgnitiveLoad.setFont(font)
        self.cgnitiveLoad.setTitle(_fromUtf8(""))
        self.cgnitiveLoad.setAlignment(QtCore.Qt.AlignCenter)
        self.cgnitiveLoad.setObjectName(_fromUtf8("cgnitiveLoad"))
        self.gridLayout_11 = QtGui.QGridLayout(self.cgnitiveLoad)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.label_7 = QtGui.QLabel(self.cgnitiveLoad)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_11.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_6 = QtGui.QLabel(self.cgnitiveLoad)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_11.addWidget(self.label_6, 0, 0, 1, 1)
        self.label_8 = QtGui.QLabel(self.cgnitiveLoad)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_11.addWidget(self.label_8, 1, 0, 1, 1)
        self.cognitiveLoadSlider = QtGui.QSlider(self.cgnitiveLoad)
        self.cognitiveLoadSlider.setMinimum(1)
        self.cognitiveLoadSlider.setMaximum(3)
        self.cognitiveLoadSlider.setPageStep(2)
        self.cognitiveLoadSlider.setOrientation(QtCore.Qt.Vertical)
        self.cognitiveLoadSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.cognitiveLoadSlider.setTickInterval(1)
        self.cognitiveLoadSlider.setObjectName(_fromUtf8("cognitiveLoadSlider"))
        self.gridLayout_11.addWidget(self.cognitiveLoadSlider, 0, 1, 3, 1)
        self.userStatusLayout.addWidget(self.cgnitiveLoad, 0, 1, 1, 1)
        self.stress = QtGui.QGroupBox(self.userStatus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.MinimumExpanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stress.sizePolicy().hasHeightForWidth())
        self.stress.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.stress.setFont(font)
        self.stress.setInputMethodHints(QtCore.Qt.ImhNone)
        self.stress.setTitle(_fromUtf8(""))
        self.stress.setAlignment(QtCore.Qt.AlignCenter)
        self.stress.setFlat(False)
        self.stress.setCheckable(False)
        self.stress.setObjectName(_fromUtf8("stress"))
        self.gridLayout_10 = QtGui.QGridLayout(self.stress)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.label_5 = QtGui.QLabel(self.stress)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_10.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtGui.QLabel(self.stress)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_10.addWidget(self.label_9, 2, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.stress)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_10.addWidget(self.label_10, 1, 0, 1, 1)
        self.stressSlider = QtGui.QSlider(self.stress)
        self.stressSlider.setMinimum(1)
        self.stressSlider.setMaximum(3)
        self.stressSlider.setPageStep(2)
        self.stressSlider.setOrientation(QtCore.Qt.Vertical)
        self.stressSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.stressSlider.setTickInterval(1)
        self.stressSlider.setObjectName(_fromUtf8("stressSlider"))
        self.gridLayout_10.addWidget(self.stressSlider, 0, 1, 3, 1)
        self.userStatusLayout.addWidget(self.stress, 0, 0, 1, 1)
        self.userLayout.addWidget(self.userStatus)
        self.groupBox_6 = QtGui.QGroupBox(self.user)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.groupBox_6.setFont(font)
        self.groupBox_6.setFlat(True)
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_13 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setHorizontalSpacing(25)
        self.gridLayout_13.setVerticalSpacing(3)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.label_18 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_13.addWidget(self.label_18, 1, 0, 1, 1)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_22.setFont(font)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_13.addWidget(self.label_22, 1, 3, 1, 1)
        self.label_23 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_23.setFont(font)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_13.addWidget(self.label_23, 1, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_24.setFont(font)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_13.addWidget(self.label_24, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_25.setFont(font)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_13.addWidget(self.label_25, 1, 4, 1, 1)
        self.costSlider = QtGui.QSlider(self.groupBox_6)
        self.costSlider.setMinimum(0)
        self.costSlider.setMaximum(100)
        self.costSlider.setProperty("value", 0)
        self.costSlider.setOrientation(QtCore.Qt.Horizontal)
        self.costSlider.setTickPosition(QtGui.QSlider.TicksBelow)
        self.costSlider.setTickInterval(5)
        self.costSlider.setObjectName(_fromUtf8("costSlider"))
        self.gridLayout_13.addWidget(self.costSlider, 0, 0, 1, 5)
        self.userLayout.addWidget(self.groupBox_6)
        self.tab1Layout.addWidget(self.user)
        self.taskContext = QtGui.QGroupBox(self.Tab1)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.taskContext.setFont(font)
        self.taskContext.setObjectName(_fromUtf8("taskContext"))
        self.gridLayout_2 = QtGui.QGridLayout(self.taskContext)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.joystick = QtGui.QGroupBox(self.taskContext)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.joystick.setFont(font)
        self.joystick.setFlat(True)
        self.joystick.setObjectName(_fromUtf8("joystick"))
        self.gridLayout_4 = QtGui.QGridLayout(self.joystick)
        self.gridLayout_4.setContentsMargins(0, 3, 0, 0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.direction_label = QtGui.QLabel(self.joystick)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.direction_label.setFont(font)
        self.direction_label.setObjectName(_fromUtf8("direction_label"))
        self.gridLayout_4.addWidget(self.direction_label, 0, 0, 1, 1)
        self.direction = QtGui.QLabel(self.joystick)
        self.direction.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.direction.setFont(font)
        self.direction.setFrameShape(QtGui.QFrame.StyledPanel)
        self.direction.setObjectName(_fromUtf8("direction"))
        self.gridLayout_4.addWidget(self.direction, 0, 1, 1, 1)
        self.toggle = QtGui.QRadioButton(self.joystick)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.toggle.setFont(font)
        self.toggle.setChecked(True)
        self.toggle.setObjectName(_fromUtf8("toggle"))
        self.joystickButtonGroup = QtGui.QButtonGroup(AUIParameters)
        self.joystickButtonGroup.setObjectName(_fromUtf8("joystickButtonGroup"))
        self.joystickButtonGroup.addButton(self.toggle)
        self.gridLayout_4.addWidget(self.toggle, 1, 0, 1, 1)
        self.sustained = QtGui.QRadioButton(self.joystick)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.sustained.setFont(font)
        self.sustained.setObjectName(_fromUtf8("sustained"))
        self.joystickButtonGroup.addButton(self.sustained)
        self.gridLayout_4.addWidget(self.sustained, 1, 1, 1, 1)
        self.gridLayout_2.addWidget(self.joystick, 1, 0, 1, 1)
        self.focus = QtGui.QGroupBox(self.taskContext)
        self.focus.setFlat(True)
        self.focus.setObjectName(_fromUtf8("focus"))
        self.gridLayout_6 = QtGui.QGridLayout(self.focus)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setSpacing(-1)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.values = QtGui.QLabel(self.focus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.values.setFont(font)
        self.values.setText(_fromUtf8(""))
        self.values.setObjectName(_fromUtf8("values"))
        self.gridLayout_6.addWidget(self.values, 1, 1, 1, 1)
        self.currentWidget = QtGui.QLabel(self.focus)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentWidget.sizePolicy().hasHeightForWidth())
        self.currentWidget.setSizePolicy(sizePolicy)
        self.currentWidget.setMinimumSize(QtCore.QSize(0, 20))
        self.currentWidget.setMaximumSize(QtCore.QSize(16777215, 44))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.currentWidget.setFont(font)
        self.currentWidget.setFrameShape(QtGui.QFrame.StyledPanel)
        self.currentWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.currentWidget.setAlignment(QtCore.Qt.AlignCenter)
        self.currentWidget.setObjectName(_fromUtf8("currentWidget"))
        self.gridLayout_6.addWidget(self.currentWidget, 0, 0, 1, 2)
        self.keys = QtGui.QLabel(self.focus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.keys.setFont(font)
        self.keys.setText(_fromUtf8(""))
        self.keys.setObjectName(_fromUtf8("keys"))
        self.gridLayout_6.addWidget(self.keys, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.focus, 4, 0, 1, 1)
        self.context = QtGui.QGroupBox(self.taskContext)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.context.setFont(font)
        self.context.setFlat(True)
        self.context.setObjectName(_fromUtf8("context"))
        self.gridLayout_5 = QtGui.QGridLayout(self.context)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.exploring = QtGui.QRadioButton(self.context)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exploring.setFont(font)
        self.exploring.setObjectName(_fromUtf8("exploring"))
        self.contextButtonGroup = QtGui.QButtonGroup(AUIParameters)
        self.contextButtonGroup.setObjectName(_fromUtf8("contextButtonGroup"))
        self.contextButtonGroup.addButton(self.exploring)
        self.gridLayout_5.addWidget(self.exploring, 2, 0, 1, 1)
        self.navigation = QtGui.QRadioButton(self.context)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.navigation.setFont(font)
        self.navigation.setChecked(True)
        self.navigation.setObjectName(_fromUtf8("navigation"))
        self.contextButtonGroup.addButton(self.navigation)
        self.gridLayout_5.addWidget(self.navigation, 1, 0, 1, 1)
        self.mapping = QtGui.QRadioButton(self.context)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.mapping.setFont(font)
        self.mapping.setObjectName(_fromUtf8("mapping"))
        self.contextButtonGroup.addButton(self.mapping)
        self.gridLayout_5.addWidget(self.mapping, 1, 1, 1, 1, QtCore.Qt.AlignVCenter)
        self.inspection = QtGui.QRadioButton(self.context)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.inspection.setFont(font)
        self.inspection.setObjectName(_fromUtf8("inspection"))
        self.contextButtonGroup.addButton(self.inspection)
        self.gridLayout_5.addWidget(self.inspection, 2, 1, 1, 1)
        self.gridLayout_2.addWidget(self.context, 3, 0, 1, 1)
        self.tab1Layout.addWidget(self.taskContext)
        self.robotStatus = QtGui.QGroupBox(self.Tab1)
        self.robotStatus.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.robotStatus.setObjectName(_fromUtf8("robotStatus"))
        self.AUIStatusLayout = QtGui.QVBoxLayout(self.robotStatus)
        self.AUIStatusLayout.setSpacing(0)
        self.AUIStatusLayout.setMargin(0)
        self.AUIStatusLayout.setObjectName(_fromUtf8("AUIStatusLayout"))
        self.AUIbatteryLevel = QtGui.QGroupBox(self.robotStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AUIbatteryLevel.setFont(font)
        self.AUIbatteryLevel.setFlat(True)
        self.AUIbatteryLevel.setObjectName(_fromUtf8("AUIbatteryLevel"))
        self.gridLayout_7 = QtGui.QGridLayout(self.AUIbatteryLevel)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setHorizontalSpacing(25)
        self.gridLayout_7.setVerticalSpacing(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.label_13 = QtGui.QLabel(self.AUIbatteryLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_13.setFont(font)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_7.addWidget(self.label_13, 0, 2, 1, 1)
        self.label_12 = QtGui.QLabel(self.AUIbatteryLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_7.addWidget(self.label_12, 0, 4, 1, 1)
        self.label_14 = QtGui.QLabel(self.AUIbatteryLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_14.setFont(font)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_7.addWidget(self.label_14, 0, 1, 1, 1)
        self.label_11 = QtGui.QLabel(self.AUIbatteryLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_7.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_15 = QtGui.QLabel(self.AUIbatteryLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_7.addWidget(self.label_15, 0, 3, 1, 1)
        self.batterySlider = QtGui.QSlider(self.AUIbatteryLevel)
        self.batterySlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.batterySlider.setMaximum(100)
        self.batterySlider.setProperty("value", 100)
        self.batterySlider.setOrientation(QtCore.Qt.Horizontal)
        self.batterySlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.batterySlider.setTickInterval(25)
        self.batterySlider.setObjectName(_fromUtf8("batterySlider"))
        self.gridLayout_7.addWidget(self.batterySlider, 2, 0, 1, 5)
        self.AUIStatusLayout.addWidget(self.AUIbatteryLevel)
        self.AUIwifiLevel = QtGui.QGroupBox(self.robotStatus)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.AUIwifiLevel.setFont(font)
        self.AUIwifiLevel.setFlat(True)
        self.AUIwifiLevel.setObjectName(_fromUtf8("AUIwifiLevel"))
        self.gridLayout_8 = QtGui.QGridLayout(self.AUIwifiLevel)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setHorizontalSpacing(25)
        self.gridLayout_8.setVerticalSpacing(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.label_20 = QtGui.QLabel(self.AUIwifiLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_20.setFont(font)
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setIndent(0)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 0, 2, 1, 1)
        self.label_19 = QtGui.QLabel(self.AUIwifiLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setIndent(0)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_8.addWidget(self.label_19, 0, 1, 1, 1)
        self.label_21 = QtGui.QLabel(self.AUIwifiLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setIndent(0)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 0, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.AUIwifiLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setIndent(0)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_8.addWidget(self.label_17, 0, 4, 1, 1)
        self.label_16 = QtGui.QLabel(self.AUIwifiLevel)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setIndent(0)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_8.addWidget(self.label_16, 0, 0, 1, 1)
        self.wifiSlider = QtGui.QSlider(self.AUIwifiLevel)
        self.wifiSlider.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wifiSlider.setMaximum(100)
        self.wifiSlider.setProperty("value", 100)
        self.wifiSlider.setOrientation(QtCore.Qt.Horizontal)
        self.wifiSlider.setTickPosition(QtGui.QSlider.TicksAbove)
        self.wifiSlider.setTickInterval(25)
        self.wifiSlider.setObjectName(_fromUtf8("wifiSlider"))
        self.gridLayout_8.addWidget(self.wifiSlider, 1, 0, 1, 5)
        self.AUIStatusLayout.addWidget(self.AUIwifiLevel)
        self.tab1Layout.addWidget(self.robotStatus)
        self.contents.addTab(self.Tab1, _fromUtf8(""))
        self.Tab3 = QtGui.QWidget()
        self.Tab3.setObjectName(_fromUtf8("Tab3"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.Tab3)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.groupBox = QtGui.QGroupBox(self.Tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.groupBox)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.groupBox_2 = QtGui.QGroupBox(self.groupBox)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.label = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.verticalLayout_5.addWidget(self.label)
        self.systemInfo = QtGui.QGroupBox(self.groupBox_2)
        self.systemInfo.setObjectName(_fromUtf8("systemInfo"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout(self.systemInfo)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setMargin(0)
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.info = QtGui.QLabel(self.systemInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.info.sizePolicy().hasHeightForWidth())
        self.info.setSizePolicy(sizePolicy)
        self.info.setMinimumSize(QtCore.QSize(0, 44))
        self.info.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.info.setFont(font)
        self.info.setObjectName(_fromUtf8("info"))
        self.horizontalLayout_4.addWidget(self.info)
        self.toolButton = QtGui.QToolButton(self.systemInfo)
        self.toolButton.setObjectName(_fromUtf8("toolButton"))
        self.horizontalLayout_4.addWidget(self.toolButton)
        self.verticalLayout_5.addWidget(self.systemInfo)
        self.episodes = QtGui.QGroupBox(self.groupBox_2)
        self.episodes.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.episodes.setObjectName(_fromUtf8("episodes"))
        self.episodesLayout = QtGui.QGridLayout(self.episodes)
        self.episodesLayout.setContentsMargins(0, 0, 0, 1)
        self.episodesLayout.setVerticalSpacing(2)
        self.episodesLayout.setObjectName(_fromUtf8("episodesLayout"))
        self.episodeTimer = QtGui.QLCDNumber(self.episodes)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.episodeTimer.sizePolicy().hasHeightForWidth())
        self.episodeTimer.setSizePolicy(sizePolicy)
        self.episodeTimer.setMinimumSize(QtCore.QSize(0, 30))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.episodeTimer.setFont(font)
        self.episodeTimer.setFrameShape(QtGui.QFrame.NoFrame)
        self.episodeTimer.setFrameShadow(QtGui.QFrame.Plain)
        self.episodeTimer.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.episodeTimer.setObjectName(_fromUtf8("episodeTimer"))
        self.episodesLayout.addWidget(self.episodeTimer, 2, 0, 1, 3)
        self.startEpisodeButton = QtGui.QPushButton(self.episodes)
        self.startEpisodeButton.setCheckable(False)
        self.startEpisodeButton.setFlat(False)
        self.startEpisodeButton.setObjectName(_fromUtf8("startEpisodeButton"))
        self.episodesLayout.addWidget(self.startEpisodeButton, 1, 0, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.stopEpisodeButton = QtGui.QPushButton(self.episodes)
        self.stopEpisodeButton.setCheckable(False)
        self.stopEpisodeButton.setObjectName(_fromUtf8("stopEpisodeButton"))
        self.episodesLayout.addWidget(self.stopEpisodeButton, 1, 1, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.resetEpisodeButton = QtGui.QPushButton(self.episodes)
        self.resetEpisodeButton.setAutoFillBackground(False)
        self.resetEpisodeButton.setAutoDefault(True)
        self.resetEpisodeButton.setDefault(False)
        self.resetEpisodeButton.setFlat(False)
        self.resetEpisodeButton.setObjectName(_fromUtf8("resetEpisodeButton"))
        self.episodesLayout.addWidget(self.resetEpisodeButton, 1, 2, 1, 1, QtCore.Qt.AlignHCenter|QtCore.Qt.AlignVCenter)
        self.verticalLayout_5.addWidget(self.episodes)
        self.currentContext = QtGui.QComboBox(self.groupBox_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.currentContext.sizePolicy().hasHeightForWidth())
        self.currentContext.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.currentContext.setFont(font)
        self.currentContext.setSizeAdjustPolicy(QtGui.QComboBox.AdjustToContents)
        self.currentContext.setFrame(True)
        self.currentContext.setObjectName(_fromUtf8("currentContext"))
        self.currentContext.addItem(_fromUtf8(""))
        self.currentContext.addItem(_fromUtf8(""))
        self.currentContext.addItem(_fromUtf8(""))
        self.currentContext.addItem(_fromUtf8(""))
        self.currentContext.addItem(_fromUtf8(""))
        self.currentContext.addItem(_fromUtf8(""))
        self.verticalLayout_5.addWidget(self.currentContext)
        self.userInfo = QtGui.QGroupBox(self.groupBox_2)
        self.userInfo.setObjectName(_fromUtf8("userInfo"))
        self.gridLayout = QtGui.QGridLayout(self.userInfo)
        self.gridLayout.setMargin(0)
        self.gridLayout.setVerticalSpacing(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.roleLabel = QtGui.QLabel(self.userInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.roleLabel.sizePolicy().hasHeightForWidth())
        self.roleLabel.setSizePolicy(sizePolicy)
        self.roleLabel.setMinimumSize(QtCore.QSize(0, 44))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.roleLabel.setFont(font)
        self.roleLabel.setObjectName(_fromUtf8("roleLabel"))
        self.gridLayout.addWidget(self.roleLabel, 0, 0, 1, 1)
        self.role = QtGui.QComboBox(self.userInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.role.sizePolicy().hasHeightForWidth())
        self.role.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.role.setFont(font)
        self.role.setObjectName(_fromUtf8("role"))
        self.role.addItem(_fromUtf8(""))
        self.role.addItem(_fromUtf8(""))
        self.role.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.role, 0, 1, 1, 1)
        self.expLabel = QtGui.QLabel(self.userInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.expLabel.sizePolicy().hasHeightForWidth())
        self.expLabel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.expLabel.setFont(font)
        self.expLabel.setObjectName(_fromUtf8("expLabel"))
        self.gridLayout.addWidget(self.expLabel, 1, 0, 1, 1)
        self.exp = QtGui.QComboBox(self.userInfo)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Maximum, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.exp.sizePolicy().hasHeightForWidth())
        self.exp.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exp.setFont(font)
        self.exp.setObjectName(_fromUtf8("exp"))
        self.exp.addItem(_fromUtf8(""))
        self.exp.addItem(_fromUtf8(""))
        self.gridLayout.addWidget(self.exp, 1, 1, 1, 1)
        self.verticalLayout_5.addWidget(self.userInfo)
        self.verticalLayout_3.addWidget(self.groupBox_2)
        self.verticalLayout_2.addWidget(self.groupBox)
        self.contents.addTab(self.Tab3, _fromUtf8(""))
        self.verticalLayout.addWidget(self.contents)
        AUIParameters.setWidget(self.AUIParams)

        self.retranslateUi(AUIParameters)
        self.contents.setCurrentIndex(0)
        QtCore.QObject.connect(self.groupBox_6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.costSlider.setEnabled)
        QtCore.QObject.connect(self.groupBox_6, QtCore.SIGNAL(_fromUtf8("clicked(bool)")), self.costSlider.setVisible)
        QtCore.QMetaObject.connectSlotsByName(AUIParameters)

    def retranslateUi(self, AUIParameters):
        AUIParameters.setWindowTitle(_translate("AUIParameters", "AUI Parameters", None))
        self.groupBox_4.setTitle(_translate("AUIParameters", "Decision Path", None))
        self.user.setTitle(_translate("AUIParameters", "User", None))
        self.userStatus.setTitle(_translate("AUIParameters", "Status", None))
        self.stressLabel.setText(_translate("AUIParameters", "Stress Level", None))
        self.cognitiveLoadLabel.setText(_translate("AUIParameters", "Cognitive Load", None))
        self.saLabel.setText(_translate("AUIParameters", "Situation Awareness", None))
        self.label_3.setText(_translate("AUIParameters", "Lv. 1", None))
        self.label_2.setText(_translate("AUIParameters", "Lv. 3", None))
        self.label_4.setText(_translate("AUIParameters", "Lv. 2", None))
        self.label_7.setText(_translate("AUIParameters", "Low", None))
        self.label_6.setText(_translate("AUIParameters", "High", None))
        self.label_8.setText(_translate("AUIParameters", "Med", None))
        self.label_5.setText(_translate("AUIParameters", "High", None))
        self.label_9.setText(_translate("AUIParameters", "Low", None))
        self.label_10.setText(_translate("AUIParameters", "Med", None))
        self.groupBox_6.setTitle(_translate("AUIParameters", "Cost", None))
        self.label_18.setText(_translate("AUIParameters", "0", None))
        self.label_22.setText(_translate("AUIParameters", "75", None))
        self.label_23.setText(_translate("AUIParameters", "25", None))
        self.label_24.setText(_translate("AUIParameters", "50", None))
        self.label_25.setText(_translate("AUIParameters", "100", None))
        self.taskContext.setTitle(_translate("AUIParameters", "Input", None))
        self.joystick.setTitle(_translate("AUIParameters", "Joystick", None))
        self.direction_label.setText(_translate("AUIParameters", "Joystick Direction", None))
        self.direction.setText(_translate("AUIParameters", "False", None))
        self.toggle.setText(_translate("AUIParameters", "Toggle", None))
        self.sustained.setText(_translate("AUIParameters", "Sustained", None))
        self.focus.setTitle(_translate("AUIParameters", "Focus", None))
        self.currentWidget.setText(_translate("AUIParameters", "<No Widget>", None))
        self.context.setTitle(_translate("AUIParameters", "Context", None))
        self.exploring.setText(_translate("AUIParameters", "Exploration", None))
        self.navigation.setText(_translate("AUIParameters", "Navigation", None))
        self.mapping.setText(_translate("AUIParameters", "Mapping", None))
        self.inspection.setText(_translate("AUIParameters", "Inspection", None))
        self.robotStatus.setTitle(_translate("AUIParameters", "Robot status", None))
        self.AUIbatteryLevel.setTitle(_translate("AUIParameters", "Battery", None))
        self.label_13.setText(_translate("AUIParameters", "50", None))
        self.label_12.setText(_translate("AUIParameters", "100", None))
        self.label_14.setText(_translate("AUIParameters", "25", None))
        self.label_11.setText(_translate("AUIParameters", "0", None))
        self.label_15.setText(_translate("AUIParameters", "75", None))
        self.AUIwifiLevel.setTitle(_translate("AUIParameters", "WiFi", None))
        self.label_20.setText(_translate("AUIParameters", "50", None))
        self.label_19.setText(_translate("AUIParameters", "25", None))
        self.label_21.setText(_translate("AUIParameters", "75", None))
        self.label_17.setText(_translate("AUIParameters", "100", None))
        self.label_16.setText(_translate("AUIParameters", "0", None))
        self.contents.setTabText(self.contents.indexOf(self.Tab1), _translate("AUIParameters", "Evidence", None))
        self.groupBox.setTitle(_translate("AUIParameters", "Probabilities", None))
        self.groupBox_2.setTitle(_translate("AUIParameters", "Context", None))
        self.label.setText(_translate("AUIParameters", "Detection", None))
        self.systemInfo.setTitle(_translate("AUIParameters", "System Information", None))
        self.info.setText(_translate("AUIParameters", "Screen Size: ", None))
        self.toolButton.setText(_translate("AUIParameters", "...", None))
        self.episodes.setTitle(_translate("AUIParameters", "Episodes", None))
        self.startEpisodeButton.setText(_translate("AUIParameters", "Start", None))
        self.stopEpisodeButton.setText(_translate("AUIParameters", "Stop", None))
        self.resetEpisodeButton.setText(_translate("AUIParameters", "New", None))
        self.currentContext.setItemText(0, _translate("AUIParameters", "<Select Task>", None))
        self.currentContext.setItemText(1, _translate("AUIParameters", "Forward navigation", None))
        self.currentContext.setItemText(2, _translate("AUIParameters", "Backward navigation", None))
        self.currentContext.setItemText(3, _translate("AUIParameters", "Camera inspection", None))
        self.currentContext.setItemText(4, _translate("AUIParameters", "Map review", None))
        self.currentContext.setItemText(5, _translate("AUIParameters", "New screenshot", None))
        self.userInfo.setTitle(_translate("AUIParameters", "Information", None))
        self.roleLabel.setText(_translate("AUIParameters", "Role: ", None))
        self.role.setItemText(0, _translate("AUIParameters", "Operator", None))
        self.role.setItemText(1, _translate("AUIParameters", "In-field Observer", None))
        self.role.setItemText(2, _translate("AUIParameters", "Team Leader", None))
        self.expLabel.setText(_translate("AUIParameters", "Experience: ", None))
        self.exp.setItemText(0, _translate("AUIParameters", "Basic", None))
        self.exp.setItemText(1, _translate("AUIParameters", "Advanced", None))
        self.contents.setTabText(self.contents.indexOf(self.Tab3), _translate("AUIParameters", "Variables", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    AUIParameters = QtGui.QDockWidget()
    ui = Ui_AUIParameters()
    ui.setupUi(AUIParameters)
    AUIParameters.show()
    sys.exit(app.exec_())

